### ISSUE TITLE
Demo link broken

### ISSUE THREAD

**Issue by Glench** [mavoweb/todomvc#1]
The link in the github description currently 404s: https://dmitrysharabin.github.io/todomvc/

**Comment by DmitrySharabin** [comment]
@LeaVerou Only you, Lea, can help us to fix this issue—after transferring this repo to the mavoweb, I don't own it anymore.

**Comment by LeaVerou** [comment]
This link works: https://mavoweb.github.io/todomvc/
PR?

**Comment by LeaVerou** [comment]
@DmitrySharabin I just set you as admin, so you don't need to PR

**Comment by DmitrySharabin** [comment]
Thanks for your help, Lea.

Glen, thank you for pointed this issue out. Now it's fixed.
